CREATE TABLE USUARIO (
	IDUSUARIO SERIAL PRIMARY KEY NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(150) NOT NULL
);

CREATE TABLE CAMPEONATO(
	IDCAMPEONATO SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ANO VARCHAR(4) NOT NULL
);

CREATE TABLE TIME(
	IDTIME SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE PARTIDA (
	IDPARTIDA SERIAL PRIMARY KEY,
	DATAPARTIDA DATE NOT NULL,
	HORAPARTIDA TIME NOT NULL,
	TIPO VARCHAR(10) NOT NULL,
	TIMEA INTEGER NOT NULL,
	RESULTADOA INTEGER NOT NULL,
	TIMEB INTEGER NOT NULL,
	RESULTADOB INTEGER NOT NULL,
	IDCAMPEONATO INTEGER NOT NULL
	REFERENCES CAMPEONATO
);